### ISSUE TITLE
apache error

### ISSUE THREAD

**Issue by villain** [MITRECND/WhoDat#10]
just got around to playing with the API and testing using curl and noticed an error in the apache error.log. querying via the pydat interface works fine. the error in the log:

==> error.log <==
[Sat Mar 26 19:45:44.512042 2016] [:error] [pid 8206:tid 139663402592000] {'sort': [{'dataVersion': {'order': 'asc'}}], 'query': {'filtered': {'filter': {'and': [{'term': {'domainName': u'google.com'}}, {'term': {'dataVersion': 7}}]}, 'query': {'match_all': {}}}}, 'size': 50000}

the curl command: curl http://localhost/ajax/domain/google.com/latest/

the output of the curl command is;

{"avail": 0, "total": 0, "data": [], "success": true}

**Comment by Mraoul** [comment]
Well, that looks like the generated ES query and looking at function 'search' in handler es.py, I apparently left debug code that prints out the query to stdout :/ -- I'm guessing Apache picks that up as an error.

Also, the UI uses the ajax/query endpoint when ES is being used instead of the ajax/domain and ajax/domains endpoints since it allows for the new search syntax, but the ajax/domain endpoint should work ... does your ES back-end have data populated for .com? If it does, then that, obviously, should have returned data

**Comment by villain** [comment]
ok, sorry about the late response. i deleted the indexes and re-imported them just to make sure nothing had corrupted or something similar. after doing the reimport i'm still experiencing the same thing. running the same command above I get the same results. if i run the query directly in elasticsearch its fine. also if i specify /1/ or /2/ instead of /latest/ the results are returned.

could there be an issue with the way its calculating the latest results?

**Comment by villain** [comment]
actually i think i just worked it out. i'm still doing imports and because the @whois_meta index is updated as soon as the import starts.. if it hasnt imported the domain yet then it wont return anything

**Comment by villain** [comment]
those changes sound good!
